apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

images:
  - name: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-dev
    newName: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-prod
    newTag: b7338330dfe0ba62f1de097ce7761747c92f97c9

replicas:
  - name: devops-app
    count: 2

commonLabels:
  environment: prod
