apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

images:
  - name: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-dev
    newName: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-prod
    newTag: cd6d6d60db252f16ffc6c536f8a8d6f2bb9bd075

replicas:
  - name: devops-app
    count: 2

commonLabels:
  environment: prod
