apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

images:
  - name: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-dev
    newName: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-prod
    newTag: 4f31d881cdd51e05ac27535ee75f4098642fa9d2

replicas:
  - name: devops-app
    count: 2

commonLabels:
  environment: prod
