apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

images:
  - name: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-dev
    newName: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-dev
    newTag: 403e53b2b70e340091057a09dd79600f0bb08d91

replicas:
  - name: devops-app
    count: 1

commonLabels:
  environment: dev
