apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

images:
  - name: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-dev
    newName: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-dev
    newTag: 62ffeae858fe6aef0853ff72be3b78f32afa451c

replicas:
  - name: devops-app
    count: 1

commonLabels:
  environment: dev
