apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

images:
  - name: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-dev
    newName: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-dev
    newTag: 04e8241aa07794e72f055dc2e9100cd4e3807596

replicas:
  - name: devops-app
    count: 1

commonLabels:
  environment: dev
