apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

images:
  - name: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-dev
    newName: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-dev
    newTag: 80360b6c48a78c2813e57ee63f66c3959307db9d

replicas:
  - name: devops-app
    count: 1

commonLabels:
  environment: dev
