apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

images:
  - name: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-dev
    newName: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-staging
    newTag: 252a1f6a2f4a91dcd47b1fc60f3acf15298fee63

replicas:
  - name: devops-app
    count: 1

commonLabels:
  environment: staging
