apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

images:
  - name: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-dev
    newName: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-staging
    newTag: 230afd438d48bff2e34da2a2ebf3eea82f067079

replicas:
  - name: devops-app
    count: 1

commonLabels:
  environment: staging
