apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

images:
  - name: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-dev
    newName: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-staging
    newTag: 76094b2fdc37ecd37b95574c5bec908de432b72d

replicas:
  - name: devops-app
    count: 1

commonLabels:
  environment: staging
