apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

images:
  - name: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-dev
    newName: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-staging
    newTag: 31fbd7021b45b0354c4bb1c48f176fbd02e7739f

replicas:
  - name: devops-app
    count: 1

commonLabels:
  environment: staging
