apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

images:
  - name: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-dev
    newName: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-staging
    newTag: d5f3b4a12a762ad89a4b7abf7fccdb069dfdc4f1

replicas:
  - name: devops-app
    count: 1

commonLabels:
  environment: staging
