apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

images:
  - name: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-dev
    newName: 125975759471.dkr.ecr.eu-central-1.amazonaws.com/devops-cicd-staging
    newTag: 3d69ea6c6f0851501d63ec0c23e1af6c4fca3084

replicas:
  - name: devops-app
    count: 1

commonLabels:
  environment: staging
